version: '3'
services:
    nginx_proxy:
        image: nginx:1.25.3-alpine
        container_name: nginx_proxy
        restart: "always"
        ports:
            - 4000:80
        depends_on:
            - backend
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ./frontend/build:/usr/share/nginx/html
    mysql:
        image: mysql:8.0.34
        restart: always
        ports:
          - "3306:3306"
        environment:
            MYSQL_DATABASE: db
            MYSQL_USER: user      
            MYSQL_PASSWORD: password
            MYSQL_ROOT_HOST: '%'
            MYSQL_ROOT_PASSWORD: root
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./database/data/mysql/:/var/lib/mysql
            - ./database/init:/docker-entrypoint-initdb.d
    backend:
        build: ./backend
        restart: always
        ports:
          - "9000:9000"
        depends_on:
            - mysql
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/db
            SPRING_DATASOURCE_USERNAME: user
            SPRING_DATASOURCE_PASSWORD: password
            SPRING_PROFILES_ACTIVE: dev
        